import * as XLSX from 'xlsx';
import { ExtractedInvoice } from '../types';

/**
 * Filter out invalid invoices:
 * - Excludes failed duplicate checks or failed three-way matching
 * - Deduplicates by invoice number to prevent duplicate records
 */
export function getValidVerifiedInvoices(invoices: ExtractedInvoice[]): ExtractedInvoice[] {
  const seenNumbers = new Set<string>();
  const validList: ExtractedInvoice[] = [];

  for (const inv of invoices) {
    const dupFailed = (inv.duplicateCheckResult || '').toLowerCase().includes('failed');
    const matchFailed = (inv.verificationStatus || '').toLowerCase().includes('failed') ||
                        (inv.poMatchResult || '').toLowerCase().includes('failed');
    if (dupFailed || matchFailed) {
      continue;
    }

    const invNum = inv.invoiceNumber.trim().toUpperCase();
    if (seenNumbers.has(invNum)) {
      continue;
    }
    seenNumbers.add(invNum);
    validList.push(inv);
  }

  return validList;
}

const getApprovalStatus = (inv: ExtractedInvoice) => {
  if (inv.humanReview) {
    const dec = inv.humanReview.decision as string;
    if (dec === 'Approved for Payment' || dec === 'Confirm Payment' || dec === 'Confirmed') return 'Approved Payment ✓';
    if (dec === 'Rejected Suggestion') return 'Rejected Payment';
    if (dec === 'Placed on Hold') return 'Payment On Hold';
    if (dec === 'Marked as Paid') return 'Marked as Paid';
    return inv.humanReview.decision;
  }
  if (inv.paymentStatus === 'Approved' || inv.paymentStatus === 'Scheduled') return 'Approved Payment ✓';
  if (inv.paymentStatus === 'Hold') return 'Payment On Hold';
  if (inv.paymentStatus === 'Paid') return 'Marked as Paid';
  return 'Pending Review';
};

const getApprovalDate = (inv: ExtractedInvoice) => {
  if (inv.humanReview?.reviewedAt) {
    return new Date(inv.humanReview.reviewedAt).toLocaleString('en-SG', { timeZone: 'Asia/Singapore' });
  }
  return '-';
};

/**
 * OPTION 1: "Download AP Payment Schedule"
 * Generates a single-tab workbook named AP_PAYMENT_SCHEDULE containing only records generated by this app.
 */
export function downloadApPaymentScheduleWorkbook(invoices: ExtractedInvoice[]) {
  const validInvoices = getValidVerifiedInvoices(invoices);
  const wb = XLSX.utils.book_new();

  const tabData = validInvoices.map((inv) => ({
    'Invoice_ID': inv.invoiceNumber,
    'Supplier': inv.supplierName,
    'PO_Number': inv.poNumber || 'PO-BH-2026',
    'Invoice Amount': inv.amount,
    'Invoice Issue Date': inv.invoiceDate,
    'Payment Due Date': inv.dueDate,
    'Payment Terms': inv.paymentTerms,
    'Three_Way_Matching Status': inv.verificationStatus || 'Clean Match',
    'Priority Level': inv.priority,
    'Priority Reason': inv.aiExplanation || inv.aiExplanationSimple?.whyPrioritised || inv.priorityReason,
    'AI Recommendation': inv.aiRecommendation || inv.aiExplanationSimple?.recommendedActionForUser || inv.recommendedAction,
    'Approval Status': getApprovalStatus(inv),
    'Approved / Reviewed By': inv.humanReview?.reviewedBy || (inv.paymentStatus === 'Approved' ? 'Madam Lim' : '-'),
    'Approval Date & Time': getApprovalDate(inv),
    'Review Notes / Reason': inv.humanReview?.notes || '-',
  }));

  const ws = XLSX.utils.json_to_sheet(tabData);
  
  // Auto-width
  const range = XLSX.utils.decode_range(ws['!ref'] || 'A1');
  const cols = [];
  for (let C = range.s.c; C <= range.e.c; ++C) {
    cols.push({ wch: 22 });
  }
  ws['!cols'] = cols;

  XLSX.utils.book_append_sheet(wb, ws, 'AP_PAYMENT_SCHEDULE');

  const dateStr = new Date().toISOString().slice(0, 10);
  XLSX.writeFile(wb, `AP_Payment_Report_${dateStr}.xlsx`);
}

/**
 * Standalone reference report export: Download AP Payment Report (XLSX)
 * Generates a standalone copy/export of the AP Payment Schedule for user reference.
 * Does not replace or affect the central ERP Shared Google Sheet.
 */
export function downloadApPaymentReport(invoices: ExtractedInvoice[]) {
  downloadApPaymentScheduleWorkbook(invoices);
}

/**
 * OPTION 2: "Download Full AP Audit Trail"
 * Generates a 3-tab workbook with Invoice_Extraction, Three_Way_Matching, and AP_PAYMENT_SCHEDULE.
 */
export function downloadFullAPAuditWorkbook(invoices: ExtractedInvoice[]) {
  const validInvoices = getValidVerifiedInvoices(invoices);
  const wb = XLSX.utils.book_new();

  // --- SHEET 1: Invoice_Extraction ---
  const tab1Data = validInvoices.map((inv) => ({
    'Invoice Number': inv.invoiceNumber,
    'Supplier Name': inv.supplierName,
    'PO Number': inv.poNumber || 'PO-BH-2026',
    'Invoice Date': inv.invoiceDate,
    'Invoice Amount': inv.amount,
    'Payment Terms': inv.paymentTerms,
    'Extracted Information': inv.extractedInformation || `Extracted ${inv.poNumber || ''}, GST Reg #, Line Items & Terms (${inv.paymentTerms})`,
    'Extraction Status': inv.extractionStatus || '100% Extracted & Verified',
  }));

  const ws1 = XLSX.utils.json_to_sheet(tab1Data);
  XLSX.utils.book_append_sheet(wb, ws1, 'Invoice_Extraction');

  // --- SHEET 2: Three_Way_Matching ---
  const tab2Data = validInvoices.map((inv) => ({
    'Invoice Number': inv.invoiceNumber,
    'Supplier Name': inv.supplierName,
    'PO Number': inv.poNumber || 'PO-BH-2026',
    'PO Verification': inv.poMatchResult || `Matched (${inv.poNumber || 'PO-BH-2026'})`,
    'Goods Received Verification': inv.grnMatchResult || 'Matched (GRN Received & Verified)',
    'Duplicate Invoice Checking': inv.duplicateCheckResult || 'Passed (No Duplicate Found)',
    'Matching Status': inv.verificationStatus || 'Passed',
  }));

  const ws2 = XLSX.utils.json_to_sheet(tab2Data);
  XLSX.utils.book_append_sheet(wb, ws2, 'Three_Way_Matching');

  // --- SHEET 3: AP_PAYMENT_SCHEDULE ---
  const tab3Data = validInvoices.map((inv) => ({
    'Invoice_ID': inv.invoiceNumber,
    'Supplier': inv.supplierName,
    'PO_Number': inv.poNumber || 'PO-BH-2026',
    'Invoice Amount': inv.amount,
    'Invoice Issue Date': inv.invoiceDate,
    'Payment Due Date': inv.dueDate,
    'Payment Terms': inv.paymentTerms,
    'Three_Way_Matching Status': inv.verificationStatus || 'Clean Match',
    'Priority Level': inv.priority,
    'Priority Reason': inv.aiExplanation || inv.aiExplanationSimple?.whyPrioritised || inv.priorityReason,
    'AI Recommendation': inv.aiRecommendation || inv.aiExplanationSimple?.recommendedActionForUser || inv.recommendedAction,
    'Approval Status': getApprovalStatus(inv),
    'Approved / Reviewed By': inv.humanReview?.reviewedBy || (inv.paymentStatus === 'Approved' ? 'Madam Lim' : '-'),
    'Approval Date & Time': getApprovalDate(inv),
    'Review Notes / Reason': inv.humanReview?.notes || '-',
  }));

  const ws3 = XLSX.utils.json_to_sheet(tab3Data);
  XLSX.utils.book_append_sheet(wb, ws3, 'AP_PAYMENT_SCHEDULE');

  // Auto-width adjustment
  [ws1, ws2, ws3].forEach((ws) => {
    const range = XLSX.utils.decode_range(ws['!ref'] || 'A1');
    const cols = [];
    for (let C = range.s.c; C <= range.e.c; ++C) {
      cols.push({ wch: 22 });
    }
    ws['!cols'] = cols;
  });

  const dateStr = new Date().toISOString().slice(0, 10);
  XLSX.writeFile(wb, `Full_AP_Audit_Trail_${dateStr}.xlsx`);
}

/** Legacy alias */
export function downloadFinalAPAuditWorkbook(invoices: ExtractedInvoice[]) {
  downloadFullAPAuditWorkbook(invoices);
}


